# Generated by Django 3.1.5 on 2021-01-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='post',
        ),
    ]
