# Generated by Django 3.1.5 on 2021-02-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210131_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
